services:
  # API Gateway Service (Reverse Proxy)
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phase5-api-gateway
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8080
      - BOOK_SERVICE_URL=http://book-service:8082
      - LOAN_SERVICE_URL=http://loan-service:8081
    depends_on:
      - user-service
      - book-service
      - loan-service
    networks:
      - microservices-network
    restart: unless-stopped

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: phase5-user-service
    # No external ports - only accessible through API Gateway
    volumes:
      - user-data:/app/data
      - ./user-service/users.db:/app/users.db
    networks:
      - microservices-network
    restart: unless-stopped

  # Book Service
  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    container_name: phase5-book-service
    # No external ports - only accessible through API Gateway
    volumes:
      - book-data:/app/data
      - ./book-service/books.db:/app/books.db
    networks:
      - microservices-network
    restart: unless-stopped

  # Loan Service
  loan-service:
    build:
      context: ./loan-service
      dockerfile: Dockerfile
    container_name: phase5-loan-service
    # No external ports - only accessible through API Gateway
    volumes:
      - loan-data:/app/data
      - ./loan-service/loans.db:/app/loans.db
    networks:
      - microservices-network
    restart: unless-stopped

# Named volumes for persistent data
volumes:
  user-data:
    driver: local
  book-data:
    driver: local
  loan-data:
    driver: local

# Custom network for microservices communication
networks:
  microservices-network:
    driver: bridge
